service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - ses:SendEmail
        - sqs:ReceiveMessage
      Resource: 
        - arn:aws:ses:*
        - ${self:custom.mailQueue.arn}
  
functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs: 
          arn: 
            Fn::GetAtt: 
              - MailQueue
              - Arn
          batchSize: 1
          
resources:
  Resources:
    MailQueue: 
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.mailQueue.name}
  Outputs:
    MailQueueArn:
      Value: ${self:custom.mailQueue.arn}
      Export:
        Name: ${self:custom.mailQueue.name}-Arn
    MailQueueUrl: 
      Value: ${self:custom.mailQueue.url}
      Export:
        Name: ${self:custom.mailQueue.name}-Url

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: 
      Fn::GetAtt: 
        - MailQueue
        - Arn
    url: !Ref MailQueue
  bundle:
    linting: false

